platform :ios, '9.0'
use_frameworks!

target 'PasscodeField_Example', :exclusive => true do
  pod 'PasscodeField', :path => '../'
end

target 'PasscodeField_Tests', :exclusive => true do
  pod 'PasscodeField', :path => '../'
    
  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end