use_frameworks!

target 'PasscodeField_Example' do
  pod 'PasscodeField', :path => '../'

  target 'PasscodeField_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
